-- CreateTable
CREATE TABLE `TD_Order` (
    `Order_No` INTEGER NOT NULL AUTO_INCREMENT,
    `Product_Grp_CD` VARCHAR(191) NOT NULL,
    `Customer_CD` VARCHAR(191) NOT NULL,
    `NAV_Name` VARCHAR(191) NOT NULL,
    `Product_Name` VARCHAR(191) NOT NULL,
    `NAV_Size` VARCHAR(191) NOT NULL,
    `Product_Size` VARCHAR(191) NOT NULL,
    `Tolerance` VARCHAR(191) NOT NULL,
    `Customer_Draw` VARCHAR(191) NOT NULL,
    `Company_Draw` VARCHAR(191) NOT NULL,
    `Product_Draw` VARCHAR(191) NOT NULL,
    `Quantity` VARCHAR(191) NOT NULL,
    `Pd_Target_Qty` VARCHAR(191) NOT NULL,
    `Pd_Complete_Qty` VARCHAR(191) NOT NULL,
    `I_Complete_Qty` VARCHAR(191) NOT NULL,
    `Shipment_Qty` VARCHAR(191) NOT NULL,
    `Pd_Split_Qty` VARCHAR(191) NOT NULL,
    `Pd_Calc_Qty` VARCHAR(191) NOT NULL,
    `NG_Qty` VARCHAR(191) NOT NULL,
    `Unit_CD` VARCHAR(191) NOT NULL,
    `Sales_Grp_CD` VARCHAR(191) NOT NULL,
    `Sales_Person_CD` VARCHAR(191) NOT NULL,
    `Request1_CD` VARCHAR(191) NOT NULL,
    `Request2_CD` VARCHAR(191) NOT NULL,
    `Request3_CD` VARCHAR(191) NOT NULL,
    `Material1` VARCHAR(191) NOT NULL,
    `H_Treatment1` VARCHAR(191) NOT NULL,
    `Material2` VARCHAR(191) NOT NULL,
    `H_Treatment2` VARCHAR(191) NOT NULL,
    `Material3` VARCHAR(191) NOT NULL,
    `H_Treatment3` VARCHAR(191) NOT NULL,
    `Material4` VARCHAR(191) NOT NULL,
    `H_Treatment4` VARCHAR(191) NOT NULL,
    `Material5` VARCHAR(191) NOT NULL,
    `H_Treatment5` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`Order_No`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TD_Procure` (
    `Order_No` INTEGER NOT NULL AUTO_INCREMENT,
    `Procure_No` INTEGER NOT NULL,
    `OdPc_No` INTEGER NOT NULL,
    `OdPcLn_No` INTEGER NOT NULL,
    `Vendor_CAT` VARCHAR(191) NOT NULL,
    `Vendor_CD` VARCHAR(191) NOT NULL,
    `Pc_Name` VARCHAR(191) NOT NULL,
    `Pc_Material` VARCHAR(191) NOT NULL,
    `Pc_Mate_Docu` VARCHAR(191) NOT NULL,
    `Temp_Price` DOUBLE NOT NULL,
    `Price_CD` VARCHAR(191) NOT NULL,
    `Unit_Price` DOUBLE NOT NULL,
    `Pc_Qty` INTEGER NOT NULL,
    `Pc_Unit_CD` VARCHAR(191) NOT NULL,
    `Pc_Person_CD` VARCHAR(191) NOT NULL,
    `Pc_Date` DATETIME(3) NOT NULL,
    `Pc_Req_Delivery` DATETIME(3) NOT NULL,
    `Pc_Req_Delivery_CD` VARCHAR(191) NOT NULL,
    `Pc_Ans_Delivery` DATETIME(3) NOT NULL,
    `Pc_Ans_Delivery_CD` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`Order_No`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TD_Plan` (
    `Order_No` INTEGER NOT NULL AUTO_INCREMENT,
    `Parts_No` INTEGER NOT NULL,
    `OdPt_No` INTEGER NOT NULL,
    `Parts_CD` VARCHAR(191) NOT NULL,
    `Pt_Material` VARCHAR(191) NOT NULL,
    `Pt_Qty` INTEGER NOT NULL,
    `Pt_Unit_CD` VARCHAR(191) NOT NULL,
    `Pt_Split` VARCHAR(191) NOT NULL,
    `Pt_Spare_Qty` INTEGER NOT NULL,
    `Pt_NG_Qty` INTEGER NOT NULL,
    `Pt_I_Comp_Qty` INTEGER NOT NULL,
    `Connect_Od_No` INTEGER NOT NULL,
    `Connect_Pt_No` INTEGER NOT NULL,

    PRIMARY KEY (`Order_No`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TD_Result` (
    `Order_No` INTEGER NOT NULL AUTO_INCREMENT,
    `Parts_No` INTEGER NOT NULL,
    `OdPt_No` INTEGER NOT NULL,
    `Rs_Reg_Date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Rs_Reg_Person_CD` VARCHAR(191) NOT NULL,
    `Rs_Upd_Date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Rs_Upd_Person_CD` VARCHAR(191) NOT NULL,
    `RPC1` VARCHAR(191) NOT NULL,
    `RPC2` VARCHAR(191) NOT NULL,
    `RPC3` VARCHAR(191) NOT NULL,
    `RPC4` VARCHAR(191) NOT NULL,
    `RPC5` VARCHAR(191) NOT NULL,
    `RPC6` VARCHAR(191) NOT NULL,
    `RPC7` VARCHAR(191) NOT NULL,
    `RPC8` VARCHAR(191) NOT NULL,
    `RPC9` VARCHAR(191) NOT NULL,
    `RPC10` VARCHAR(191) NOT NULL,
    `RPC11` VARCHAR(191) NOT NULL,
    `RPC12` VARCHAR(191) NOT NULL,
    `RPC13` VARCHAR(191) NOT NULL,
    `RPC14` VARCHAR(191) NOT NULL,
    `RPC15` VARCHAR(191) NOT NULL,
    `RPC16` VARCHAR(191) NOT NULL,
    `RPC17` VARCHAR(191) NOT NULL,
    `RPC18` VARCHAR(191) NOT NULL,
    `RPC19` VARCHAR(191) NOT NULL,
    `RPC20` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`Order_No`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TD_Cost` (
    `Order_No` INTEGER NOT NULL AUTO_INCREMENT,
    `Parts_No` INTEGER NOT NULL,
    `Cost_No` INTEGER NOT NULL,
    `Process_No` INTEGER NOT NULL,
    `OdPt_No` INTEGER NOT NULL,
    `OdPtCs_No` INTEGER NOT NULL,
    `OdPtPr_No` INTEGER NOT NULL,
    `CMC` VARCHAR(191) NOT NULL,
    `CMT` VARCHAR(191) NOT NULL,
    `CPC` VARCHAR(191) NOT NULL,
    `CPT` VARCHAR(191) NOT NULL,
    `CPD` VARCHAR(191) NOT NULL,
    `CPN` VARCHAR(191) NOT NULL,
    `Cs_Progress_CD` VARCHAR(191) NOT NULL,
    `Cs_Complete_Date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Cs_Complete_Qty` INTEGER NOT NULL,

    PRIMARY KEY (`Order_No`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TD_Schedule` (
    `Order_No` INTEGER NOT NULL AUTO_INCREMENT,
    `Parts_No` INTEGER NOT NULL,
    `OdPt_No` INTEGER NOT NULL,
    `Schedule_No` INTEGER NOT NULL,
    `Sc_Choice` VARCHAR(191) NOT NULL,
    `Schedule_CD` VARCHAR(191) NOT NULL,
    `Sc_Reg_Date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Sc_Reg_Person_CD` VARCHAR(191) NOT NULL,
    `Sc_Upd_Date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Sc_Upd_Person_CD` VARCHAR(191) NOT NULL,
    `PPD1` VARCHAR(191) NOT NULL,
    `PPD2` VARCHAR(191) NOT NULL,
    `PPD3` VARCHAR(191) NOT NULL,
    `PPD4` VARCHAR(191) NOT NULL,
    `PPD5` VARCHAR(191) NOT NULL,
    `PPD6` VARCHAR(191) NOT NULL,
    `PPD7` VARCHAR(191) NOT NULL,
    `PPD8` VARCHAR(191) NOT NULL,
    `PPD9` VARCHAR(191) NOT NULL,
    `PPD10` VARCHAR(191) NOT NULL,
    `PPD11` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`Order_No`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TD_WIP` (
    `Order_No` INTEGER NOT NULL AUTO_INCREMENT,
    `Parts_No` INTEGER NOT NULL,
    `Process_No` INTEGER NOT NULL,
    `OdPt_No` INTEGER NOT NULL,
    `OdPtPr_No` INTEGER NOT NULL,
    `PPG` VARCHAR(191) NOT NULL,
    `PPC` VARCHAR(191) NOT NULL,
    `PMT` VARCHAR(191) NOT NULL,
    `PPT` VARCHAR(191) NOT NULL,
    `T_Type` VARCHAR(191) NOT NULL,
    `P_Type` VARCHAR(191) NOT NULL,
    `S_Type` VARCHAR(191) NOT NULL,
    `PPD` VARCHAR(191) NOT NULL,
    `PML` VARCHAR(191) NOT NULL,
    `PPL` VARCHAR(191) NOT NULL,
    `INN` VARCHAR(191) NOT NULL,
    `RPD` VARCHAR(191) NOT NULL,
    `RMT` VARCHAR(191) NOT NULL,
    `RPT` VARCHAR(191) NOT NULL,
    `RPN` VARCHAR(191) NOT NULL,
    `ASP` VARCHAR(191) NOT NULL,
    `Now_No` VARCHAR(191) NOT NULL,
    `WIP_CAT1` VARCHAR(191) NOT NULL,
    `WIP_CAT2` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`Order_No`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TM_Process` (
    `Process_CD` VARCHAR(191) NOT NULL,
    `Change_CD` VARCHAR(191) NOT NULL,
    `ProcessG_CD` VARCHAR(191) NOT NULL,
    `ResourceG_CD` VARCHAR(191) NOT NULL,
    `ManageG_CD` VARCHAR(191) NOT NULL,
    `Manhour_Calc` VARCHAR(191) NOT NULL,
    `Days_Calc` VARCHAR(191) NOT NULL,
    `Process_Name` VARCHAR(191) NOT NULL,
    `Process_Abb` VARCHAR(191) NOT NULL,
    `Process_Symbol` VARCHAR(191) NOT NULL,
    `Process_Mark` VARCHAR(191) NOT NULL,
    `Use` VARCHAR(191) NOT NULL,
    `For_Plan` VARCHAR(191) NOT NULL,
    `For_Info` VARCHAR(191) NOT NULL,
    `Graph` VARCHAR(191) NOT NULL,
    `List` VARCHAR(191) NOT NULL,
    `Outside_On` VARCHAR(191) NOT NULL,
    `Outside_Off` VARCHAR(191) NOT NULL,
    `End` VARCHAR(191) NOT NULL,
    `Coefficient` VARCHAR(191) NOT NULL,
    `M_Coefficient` VARCHAR(191) NOT NULL,
    `P_Coefficient` VARCHAR(191) NOT NULL,
    `Before` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`Process_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TM_ProcessG` (
    `ProcessG_CD` VARCHAR(191) NOT NULL,
    `Change_CD` VARCHAR(191) NOT NULL,
    `ManageG_CD` VARCHAR(191) NOT NULL,
    `ProcessG_Name` VARCHAR(191) NOT NULL,
    `ProcessG_Abb` VARCHAR(191) NOT NULL,
    `ProcessG_Symbol` VARCHAR(191) NOT NULL,
    `ProcessG_Mark` VARCHAR(191) NOT NULL,
    `Use` VARCHAR(191) NOT NULL,
    `Use_Object` VARCHAR(191) NOT NULL,
    `Graph` VARCHAR(191) NOT NULL,
    `List` VARCHAR(191) NOT NULL,
    `Coefficient` VARCHAR(191) NOT NULL,
    `M_Coefficient` VARCHAR(191) NOT NULL,
    `P_Coefficient` VARCHAR(191) NOT NULL,
    `Std_M_CAT` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`ProcessG_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TM_ResourceG` (
    `ResourceG_CD` VARCHAR(191) NOT NULL,
    `Change_CD` VARCHAR(191) NOT NULL,
    `ResourceG_Name` VARCHAR(191) NOT NULL,
    `ResourceG_Abb` VARCHAR(191) NOT NULL,
    `ResourceG_Symbol` VARCHAR(191) NOT NULL,
    `ResourceG_Mark` VARCHAR(191) NOT NULL,
    `Us_Group_Mark` VARCHAR(191) NOT NULL,
    `Use` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`ResourceG_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TM_Resource` (
    `Resource_CD` VARCHAR(191) NOT NULL,
    `Change_CD` VARCHAR(191) NOT NULL,
    `ResourceG_CD` VARCHAR(191) NOT NULL,
    `CostG_CD` VARCHAR(191) NOT NULL,
    `ManageG_CD` VARCHAR(191) NOT NULL,
    `Resource_Name` VARCHAR(191) NOT NULL,
    `Resource_Abb` VARCHAR(191) NOT NULL,
    `Resource_Symbol` VARCHAR(191) NOT NULL,
    `Resource_Mark` VARCHAR(191) NOT NULL,
    `Use` VARCHAR(191) NOT NULL,
    `End` VARCHAR(191) NOT NULL,
    `M_Coefficient` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`Resource_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TM_CostG` (
    `CostG_CD` VARCHAR(191) NOT NULL,
    `Change_CD` VARCHAR(191) NOT NULL,
    `CostG_Name` VARCHAR(191) NOT NULL,
    `CostG_Abb` VARCHAR(191) NOT NULL,
    `CostG_Symbol` VARCHAR(191) NOT NULL,
    `CostG_Mark` VARCHAR(191) NOT NULL,
    `Use` VARCHAR(191) NOT NULL,
    `Coefficient` VARCHAR(191) NOT NULL,
    `M_Coefficient` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`CostG_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TM_WorkG` (
    `WorkG_CD` VARCHAR(191) NOT NULL,
    `WorkG_Name` VARCHAR(191) NOT NULL,
    `WorkG_Abb` VARCHAR(191) NOT NULL,
    `WorkG_Symbol` VARCHAR(191) NOT NULL,
    `WorkG_Mark` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`WorkG_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TM_Worker` (
    `Worker_CD` VARCHAR(191) NOT NULL,
    `Worker_Pass` VARCHAR(191) NOT NULL,
    `WorkerG_CD` VARCHAR(191) NOT NULL,
    `WorkG_CD` VARCHAR(191) NOT NULL,
    `Worker_Name` VARCHAR(191) NOT NULL,
    `Worker_Abb` VARCHAR(191) NOT NULL,
    `Worker_JPN` VARCHAR(191) NOT NULL,
    `Access_Lv` DOUBLE NOT NULL,
    `Worker_Level` VARCHAR(191) NOT NULL,
    `Worker_Menu` VARCHAR(191) NOT NULL,
    `Worker_Remark` VARCHAR(191) NOT NULL,
    `SSMA_TimeStamp` DATETIME(3) NULL,

    PRIMARY KEY (`Worker_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TM_WorkerG` (
    `WorkerG_CD` VARCHAR(191) NOT NULL,
    `WorkerG_Name` VARCHAR(191) NOT NULL,
    `WorkerG_Abb` VARCHAR(191) NOT NULL,
    `WorkerG_Remark` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`WorkerG_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TM_User` (
    `User_ID` VARCHAR(191) NOT NULL,
    `User_Name` VARCHAR(191) NOT NULL,
    `User_Abb` VARCHAR(191) NOT NULL,
    `User_Pass` VARCHAR(191) NOT NULL,
    `User_Remark` VARCHAR(191) NOT NULL,
    `F0100` BOOLEAN NOT NULL DEFAULT false,
    `F0101` BOOLEAN NOT NULL DEFAULT false,
    `F0102` BOOLEAN NOT NULL DEFAULT false,
    `F0103` BOOLEAN NOT NULL DEFAULT false,
    `F0104` BOOLEAN NOT NULL DEFAULT false,
    `F0105` BOOLEAN NOT NULL DEFAULT false,
    `F0106` BOOLEAN NOT NULL DEFAULT false,
    `F0107` BOOLEAN NOT NULL DEFAULT false,
    `F0108` BOOLEAN NOT NULL DEFAULT false,
    `F0109` BOOLEAN NOT NULL DEFAULT false,
    `F0110` BOOLEAN NOT NULL DEFAULT false,
    `F0112` BOOLEAN NOT NULL DEFAULT false,
    `F0113` BOOLEAN NOT NULL DEFAULT false,
    `F0114` BOOLEAN NOT NULL DEFAULT false,
    `F0115` BOOLEAN NOT NULL DEFAULT false,
    `F0116` BOOLEAN NOT NULL DEFAULT false,
    `F0117` BOOLEAN NOT NULL DEFAULT false,
    `F0118` BOOLEAN NOT NULL DEFAULT false,
    `F0119` BOOLEAN NOT NULL DEFAULT false,
    `F0120` BOOLEAN NOT NULL DEFAULT false,
    `F0200` BOOLEAN NOT NULL DEFAULT false,
    `F0201` BOOLEAN NOT NULL DEFAULT false,
    `F0202` BOOLEAN NOT NULL DEFAULT false,
    `F0203` BOOLEAN NOT NULL DEFAULT false,
    `F0204` BOOLEAN NOT NULL DEFAULT false,
    `F0205` BOOLEAN NOT NULL DEFAULT false,
    `F0206` BOOLEAN NOT NULL DEFAULT false,
    `F0207` BOOLEAN NOT NULL DEFAULT false,
    `F0208` BOOLEAN NOT NULL DEFAULT false,
    `F0209` BOOLEAN NOT NULL DEFAULT false,
    `F0210` BOOLEAN NOT NULL DEFAULT false,
    `F0211` BOOLEAN NOT NULL DEFAULT false,
    `F0212` BOOLEAN NOT NULL DEFAULT false,
    `F0213` BOOLEAN NOT NULL DEFAULT false,
    `F0214` BOOLEAN NOT NULL DEFAULT false,
    `F0215` BOOLEAN NOT NULL DEFAULT false,
    `F0216` BOOLEAN NOT NULL DEFAULT false,
    `F0217` BOOLEAN NOT NULL DEFAULT false,
    `F0218` BOOLEAN NOT NULL DEFAULT false,
    `F0219` BOOLEAN NOT NULL DEFAULT false,
    `F0220` BOOLEAN NOT NULL DEFAULT false,
    `F0300` BOOLEAN NOT NULL DEFAULT false,
    `F0301` BOOLEAN NOT NULL DEFAULT false,
    `F0302` BOOLEAN NOT NULL DEFAULT false,
    `F0303` BOOLEAN NOT NULL DEFAULT false,
    `F0304` BOOLEAN NOT NULL DEFAULT false,
    `F0305` BOOLEAN NOT NULL DEFAULT false,
    `F0306` BOOLEAN NOT NULL DEFAULT false,
    `F0307` BOOLEAN NOT NULL DEFAULT false,
    `F0308` BOOLEAN NOT NULL DEFAULT false,
    `F0309` BOOLEAN NOT NULL DEFAULT false,
    `F0310` BOOLEAN NOT NULL DEFAULT false,
    `F0311` BOOLEAN NOT NULL DEFAULT false,
    `F0312` BOOLEAN NOT NULL DEFAULT false,
    `F0313` BOOLEAN NOT NULL DEFAULT false,
    `F0314` BOOLEAN NOT NULL DEFAULT false,
    `F0315` BOOLEAN NOT NULL DEFAULT false,
    `F0316` BOOLEAN NOT NULL DEFAULT false,
    `F0317` BOOLEAN NOT NULL DEFAULT false,
    `F0318` BOOLEAN NOT NULL DEFAULT false,
    `F0319` BOOLEAN NOT NULL DEFAULT false,
    `F0320` BOOLEAN NOT NULL DEFAULT false,
    `F0400` BOOLEAN NOT NULL DEFAULT false,
    `F0401` BOOLEAN NOT NULL DEFAULT false,
    `F0402` BOOLEAN NOT NULL DEFAULT false,
    `F0403` BOOLEAN NOT NULL DEFAULT false,
    `F0404` BOOLEAN NOT NULL DEFAULT false,
    `F0405` BOOLEAN NOT NULL DEFAULT false,
    `F0406` BOOLEAN NOT NULL DEFAULT false,
    `F0407` BOOLEAN NOT NULL DEFAULT false,
    `F0408` BOOLEAN NOT NULL DEFAULT false,
    `F0409` BOOLEAN NOT NULL DEFAULT false,
    `F0410` BOOLEAN NOT NULL DEFAULT false,
    `F0411` BOOLEAN NOT NULL DEFAULT false,
    `F0412` BOOLEAN NOT NULL DEFAULT false,
    `F0413` BOOLEAN NOT NULL DEFAULT false,
    `F0414` BOOLEAN NOT NULL DEFAULT false,
    `F0415` BOOLEAN NOT NULL DEFAULT false,
    `F0416` BOOLEAN NOT NULL DEFAULT false,
    `F0417` BOOLEAN NOT NULL DEFAULT false,
    `F0418` BOOLEAN NOT NULL DEFAULT false,
    `F0419` BOOLEAN NOT NULL DEFAULT false,
    `F0420` BOOLEAN NOT NULL DEFAULT false,
    `F0500` BOOLEAN NOT NULL DEFAULT false,
    `F0501` BOOLEAN NOT NULL DEFAULT false,
    `F0502` BOOLEAN NOT NULL DEFAULT false,
    `F0503` BOOLEAN NOT NULL DEFAULT false,
    `F0504` BOOLEAN NOT NULL DEFAULT false,
    `F0505` BOOLEAN NOT NULL DEFAULT false,
    `F0506` BOOLEAN NOT NULL DEFAULT false,
    `F0507` BOOLEAN NOT NULL DEFAULT false,
    `F0508` BOOLEAN NOT NULL DEFAULT false,
    `F0509` BOOLEAN NOT NULL DEFAULT false,
    `F0510` BOOLEAN NOT NULL DEFAULT false,
    `F0511` BOOLEAN NOT NULL DEFAULT false,
    `F0512` BOOLEAN NOT NULL DEFAULT false,
    `F0513` BOOLEAN NOT NULL DEFAULT false,
    `F0514` BOOLEAN NOT NULL DEFAULT false,
    `F0515` BOOLEAN NOT NULL DEFAULT false,
    `F0516` BOOLEAN NOT NULL DEFAULT false,
    `F0517` BOOLEAN NOT NULL DEFAULT false,
    `F0518` BOOLEAN NOT NULL DEFAULT false,
    `F0519` BOOLEAN NOT NULL DEFAULT false,
    `F0520` BOOLEAN NOT NULL DEFAULT false,
    `F0600` BOOLEAN NOT NULL DEFAULT false,
    `F0601` BOOLEAN NOT NULL DEFAULT false,
    `F0602` BOOLEAN NOT NULL DEFAULT false,
    `F0603` BOOLEAN NOT NULL DEFAULT false,
    `F0604` BOOLEAN NOT NULL DEFAULT false,
    `F0605` BOOLEAN NOT NULL DEFAULT false,
    `F0606` BOOLEAN NOT NULL DEFAULT false,
    `F0607` BOOLEAN NOT NULL DEFAULT false,
    `F0608` BOOLEAN NOT NULL DEFAULT false,
    `F0609` BOOLEAN NOT NULL DEFAULT false,
    `F0610` BOOLEAN NOT NULL DEFAULT false,
    `F0611` BOOLEAN NOT NULL DEFAULT false,
    `F0612` BOOLEAN NOT NULL DEFAULT false,
    `F0613` BOOLEAN NOT NULL DEFAULT false,
    `F0614` BOOLEAN NOT NULL DEFAULT false,
    `F0615` BOOLEAN NOT NULL DEFAULT false,
    `F0616` BOOLEAN NOT NULL DEFAULT false,
    `F0617` BOOLEAN NOT NULL DEFAULT false,
    `F0618` BOOLEAN NOT NULL DEFAULT false,
    `F0619` BOOLEAN NOT NULL DEFAULT false,
    `F0620` BOOLEAN NOT NULL DEFAULT false,
    `F0700` BOOLEAN NOT NULL DEFAULT false,
    `F0701` BOOLEAN NOT NULL DEFAULT false,
    `F0702` BOOLEAN NOT NULL DEFAULT false,
    `F0703` BOOLEAN NOT NULL DEFAULT false,
    `F0704` BOOLEAN NOT NULL DEFAULT false,
    `F0705` BOOLEAN NOT NULL DEFAULT false,
    `F0706` BOOLEAN NOT NULL DEFAULT false,
    `F0707` BOOLEAN NOT NULL DEFAULT false,
    `F0708` BOOLEAN NOT NULL DEFAULT false,
    `F0709` BOOLEAN NOT NULL DEFAULT false,
    `F0710` BOOLEAN NOT NULL DEFAULT false,
    `F0711` BOOLEAN NOT NULL DEFAULT false,
    `F0712` BOOLEAN NOT NULL DEFAULT false,
    `F0713` BOOLEAN NOT NULL DEFAULT false,
    `F0714` BOOLEAN NOT NULL DEFAULT false,
    `F0715` BOOLEAN NOT NULL DEFAULT false,
    `F0716` BOOLEAN NOT NULL DEFAULT false,
    `F0717` BOOLEAN NOT NULL DEFAULT false,
    `F0718` BOOLEAN NOT NULL DEFAULT false,
    `F0719` BOOLEAN NOT NULL DEFAULT false,
    `F0720` BOOLEAN NOT NULL DEFAULT false,
    `F0800` BOOLEAN NOT NULL DEFAULT false,
    `F0801` BOOLEAN NOT NULL DEFAULT false,
    `F0802` BOOLEAN NOT NULL DEFAULT false,
    `F0803` BOOLEAN NOT NULL DEFAULT false,
    `F0804` BOOLEAN NOT NULL DEFAULT false,
    `F0805` BOOLEAN NOT NULL DEFAULT false,
    `F0806` BOOLEAN NOT NULL DEFAULT false,
    `F0807` BOOLEAN NOT NULL DEFAULT false,
    `F0808` BOOLEAN NOT NULL DEFAULT false,
    `F0809` BOOLEAN NOT NULL DEFAULT false,
    `F0810` BOOLEAN NOT NULL DEFAULT false,
    `F0811` BOOLEAN NOT NULL DEFAULT false,
    `F0812` BOOLEAN NOT NULL DEFAULT false,
    `F0813` BOOLEAN NOT NULL DEFAULT false,
    `F0814` BOOLEAN NOT NULL DEFAULT false,
    `F0815` BOOLEAN NOT NULL DEFAULT false,
    `F0816` BOOLEAN NOT NULL DEFAULT false,
    `F0817` BOOLEAN NOT NULL DEFAULT false,
    `F0818` BOOLEAN NOT NULL DEFAULT false,
    `F0819` BOOLEAN NOT NULL DEFAULT false,
    `F0820` BOOLEAN NOT NULL DEFAULT false,
    `F0900` BOOLEAN NOT NULL DEFAULT false,
    `F0901` BOOLEAN NOT NULL DEFAULT false,
    `F0902` BOOLEAN NOT NULL DEFAULT false,
    `F0903` BOOLEAN NOT NULL DEFAULT false,
    `F0904` BOOLEAN NOT NULL DEFAULT false,
    `F0905` BOOLEAN NOT NULL DEFAULT false,
    `F0906` BOOLEAN NOT NULL DEFAULT false,
    `F0907` BOOLEAN NOT NULL DEFAULT false,
    `F0908` BOOLEAN NOT NULL DEFAULT false,
    `F0909` BOOLEAN NOT NULL DEFAULT false,
    `F0910` BOOLEAN NOT NULL DEFAULT false,
    `F0911` BOOLEAN NOT NULL DEFAULT false,
    `F0912` BOOLEAN NOT NULL DEFAULT false,
    `F0913` BOOLEAN NOT NULL DEFAULT false,
    `F0914` BOOLEAN NOT NULL DEFAULT false,
    `F0915` BOOLEAN NOT NULL DEFAULT false,
    `F0916` BOOLEAN NOT NULL DEFAULT false,
    `F0917` BOOLEAN NOT NULL DEFAULT false,
    `F0918` BOOLEAN NOT NULL DEFAULT false,
    `F0919` BOOLEAN NOT NULL DEFAULT false,
    `F0920` BOOLEAN NOT NULL DEFAULT false,
    `F1000` BOOLEAN NOT NULL DEFAULT false,
    `F1001` BOOLEAN NOT NULL DEFAULT false,
    `F1002` BOOLEAN NOT NULL DEFAULT false,
    `F1003` BOOLEAN NOT NULL DEFAULT false,
    `F1004` BOOLEAN NOT NULL DEFAULT false,
    `F1005` BOOLEAN NOT NULL DEFAULT false,
    `F1006` BOOLEAN NOT NULL DEFAULT false,
    `F1007` BOOLEAN NOT NULL DEFAULT false,
    `F1008` BOOLEAN NOT NULL DEFAULT false,
    `F1009` BOOLEAN NOT NULL DEFAULT false,
    `F1010` BOOLEAN NOT NULL DEFAULT false,
    `F1011` BOOLEAN NOT NULL DEFAULT false,
    `F1012` BOOLEAN NOT NULL DEFAULT false,
    `F1013` BOOLEAN NOT NULL DEFAULT false,
    `F1014` BOOLEAN NOT NULL DEFAULT false,
    `F1015` BOOLEAN NOT NULL DEFAULT false,
    `F1016` BOOLEAN NOT NULL DEFAULT false,
    `F1017` BOOLEAN NOT NULL DEFAULT false,
    `F1018` BOOLEAN NOT NULL DEFAULT false,
    `F1019` BOOLEAN NOT NULL DEFAULT false,
    `F1020` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`User_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `_ProcessGroupProcesses` (
    `A` VARCHAR(191) NOT NULL,
    `B` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `_ProcessGroupProcesses_AB_unique`(`A`, `B`),
    INDEX `_ProcessGroupProcesses_B_index`(`B`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `_WorkGroupWorkers` (
    `A` VARCHAR(191) NOT NULL,
    `B` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `_WorkGroupWorkers_AB_unique`(`A`, `B`),
    INDEX `_WorkGroupWorkers_B_index`(`B`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `_WorkerWorkerGroups` (
    `A` VARCHAR(191) NOT NULL,
    `B` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `_WorkerWorkerGroups_AB_unique`(`A`, `B`),
    INDEX `_WorkerWorkerGroups_B_index`(`B`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `TD_Procure` ADD CONSTRAINT `TD_Procure_Order_No_fkey` FOREIGN KEY (`Order_No`) REFERENCES `TD_Order`(`Order_No`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TD_Plan` ADD CONSTRAINT `TD_Plan_Order_No_fkey` FOREIGN KEY (`Order_No`) REFERENCES `TD_Order`(`Order_No`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TD_Result` ADD CONSTRAINT `TD_Result_Order_No_fkey` FOREIGN KEY (`Order_No`) REFERENCES `TD_Order`(`Order_No`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TD_Cost` ADD CONSTRAINT `TD_Cost_Order_No_fkey` FOREIGN KEY (`Order_No`) REFERENCES `TD_Order`(`Order_No`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TD_Schedule` ADD CONSTRAINT `TD_Schedule_Order_No_fkey` FOREIGN KEY (`Order_No`) REFERENCES `TD_Order`(`Order_No`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TD_WIP` ADD CONSTRAINT `TD_WIP_Order_No_fkey` FOREIGN KEY (`Order_No`) REFERENCES `TD_Order`(`Order_No`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TM_Process` ADD CONSTRAINT `TM_Process_Process_CD_fkey` FOREIGN KEY (`Process_CD`) REFERENCES `TM_Resource`(`Resource_CD`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TM_Process` ADD CONSTRAINT `TM_Process_ProcessG_CD_fkey` FOREIGN KEY (`ProcessG_CD`) REFERENCES `TM_ProcessG`(`ProcessG_CD`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TM_Worker` ADD CONSTRAINT `TM_Worker_WorkG_CD_fkey` FOREIGN KEY (`WorkG_CD`) REFERENCES `TM_WorkG`(`WorkG_CD`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `_ProcessGroupProcesses` ADD CONSTRAINT `_ProcessGroupProcesses_A_fkey` FOREIGN KEY (`A`) REFERENCES `TM_Process`(`Process_CD`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `_ProcessGroupProcesses` ADD CONSTRAINT `_ProcessGroupProcesses_B_fkey` FOREIGN KEY (`B`) REFERENCES `TM_ProcessG`(`ProcessG_CD`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `_WorkGroupWorkers` ADD CONSTRAINT `_WorkGroupWorkers_A_fkey` FOREIGN KEY (`A`) REFERENCES `TM_WorkG`(`WorkG_CD`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `_WorkGroupWorkers` ADD CONSTRAINT `_WorkGroupWorkers_B_fkey` FOREIGN KEY (`B`) REFERENCES `TM_Worker`(`Worker_CD`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `_WorkerWorkerGroups` ADD CONSTRAINT `_WorkerWorkerGroups_A_fkey` FOREIGN KEY (`A`) REFERENCES `TM_Worker`(`Worker_CD`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `_WorkerWorkerGroups` ADD CONSTRAINT `_WorkerWorkerGroups_B_fkey` FOREIGN KEY (`B`) REFERENCES `TM_WorkerG`(`WorkerG_CD`) ON DELETE CASCADE ON UPDATE CASCADE;
